#!/usr/bin/env bash
# Recreate the legacy oracle copies from ../docs.
#   legacy/          pristine, frozen copy of docs/ (behavior + visual oracle)
#   legacy-shimmed/  docs/ + minimal swappable shims (the harness drives this)
# Both are gitignored and regenerated by this script (keeps the repo free of
# duplicated source). Run from web/.
set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf legacy legacy-shimmed
cp -r ../docs legacy
cp -r ../docs legacy-shimmed

# Apply the swappable-provider shims to legacy-shimmed (added in M2).
if [ -f scripts/apply-shims.mjs ]; then
  node scripts/apply-shims.mjs legacy-shimmed
fi

echo "legacy/ and legacy-shimmed/ recreated from ../docs"
