#!/usr/bin/env bash
# Recreate the legacy oracle copies from ../legacy (the tracked, frozen copy of
# the original app — formerly ../docs, relocated so docs/ holds the built new app
# for GitHub Pages).
#   legacy/          pristine, frozen copy (behavior + visual oracle)
#   legacy-shimmed/  the legacy app + minimal swappable shims (the harness drives this)
# Both web/legacy and web/legacy-shimmed are gitignored and regenerated by this
# script (keeps web/ free of duplicated source). Run from web/.
set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf legacy legacy-shimmed
cp -r ../legacy legacy
cp -r ../legacy legacy-shimmed

# Apply the swappable-provider shims to legacy-shimmed (added in M2).
if [ -f scripts/apply-shims.mjs ]; then
  node scripts/apply-shims.mjs legacy-shimmed
fi

echo "legacy/ and legacy-shimmed/ recreated from ../legacy"
